### ISSUE TITLE
Question:怎么查看tensorflow的c++接口安装在哪里

### ISSUE THREAD

**Issue by 17829686892** [chenglabwiki/chenglabwiki.github.io#100]
Question on: https://github.com/chenggroup/chenggroup.github.io/tree/master/_wiki/软件安装/deepmd-kit_installation_51.md#整合运行库与头文件

**Comment by 17829686892** [comment]
如何查看tensorflow的c++接口安装在哪里

**Comment by Cloudac7** [comment]
> 如何查看tensorflow的c++接口安装在哪里

根据这份文档里的说明，是从编译目录（上一步所在的目录）把C++接口复制到`tensorflow_root`下，即这里所定义的`/some/workspace/tensorflow_root`

**Comment by 17829686892** [comment]
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package ***@***.***_bazel_rules_closure//closure': java.io.IOException: Error downloading [http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz, https://github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz] to /gpfs1/home/nc/hpc2/.cache/bazel/_bazel_hpc2.nc/63c7f906a6d51cd9e5ec891281eeb194/external/io_bazel_rules_closure/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz: All mirrors are down: [Unknown host: github.com, Unknown host: mirror.tensorflow.org]
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package ***@***.***_bazel_rules_closure//closure': java.io.IOException: Error downloading [http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz, https://github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz] to /gpfs1/home/nc/hpc2/.cache/bazel/_bazel_hpc2.nc/63c7f906a6d51cd9e5ec891281eeb194/external/io_bazel_rules_closure/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz: All mirrors are down: [Unknown host: github.com, Unknown host: mirror.tensorflow.org]
INFO: Elapsed time: 12.045s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

请问您知道这个是怎么回事吗？这个是我在执行bazel build -c opt --verbose_failures //tensorflow:libtensorflow_cc.so时出现的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenggroup/chenggroup.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月14日(星期五) 晚上9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenggroup/chenggroup.github.io] Question:怎么查看tensorflow的c++接口安装在哪里 (Issue #100)





  
如何查看tensorflow的c++接口安装在哪里
  
根据这份文档里的说明，是从编译目录（上一步所在的目录）把C++接口复制到tensorflow_root下，即这里所定义的/some/workspace/tensorflow_root
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Cloudac7** [comment]
> ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package ***@***.***_bazel_rules_closure//closure': java.io.IOException: Error downloading [http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz, https://github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz] to /gpfs1/home/nc/hpc2/.cache/bazel/_bazel_hpc2.nc/63c7f906a6d51cd9e5ec891281eeb194/external/io_bazel_rules_closure/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz: All mirrors are down: [Unknown host: github.com, Unknown host: mirror.tensorflow.org]
> ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package ***@***.***_bazel_rules_closure//closure': java.io.IOException: Error downloading [http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz, https://github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz] to /gpfs1/home/nc/hpc2/.cache/bazel/_bazel_hpc2.nc/63c7f906a6d51cd9e5ec891281eeb194/external/io_bazel_rules_closure/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz: All mirrors are down: [Unknown host: github.com, Unknown host: mirror.tensorflow.org]
> INFO: Elapsed time: 12.045s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded)
> 
> 请问您知道这个是怎么回事吗？这个是我在执行bazel build -c opt --verbose_failures //tensorflow:libtensorflow_cc.so时出现的
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "chenggroup/chenggroup.github.io"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2022年1月14日(星期五) 晚上9:21
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [chenggroup/chenggroup.github.io] Question:怎么查看tensorflow的c++接口安装在哪里 (Issue #100)
> 
> 
> 
> 
> 
>   
> 如何查看tensorflow的c++接口安装在哪里
>   
> 根据这份文档里的说明，是从编译目录（上一步所在的目录）把C++接口复制到tensorflow_root下，即这里所定义的/some/workspace/tensorflow_root
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

根据报错信息，应当是github访问超时。
