### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by LavendaRaphael** [chenglabwiki/chenglabwiki.github.io#109]
Question on: https://github.com/chenggroup/chenggroup.github.io/tree/master/_wiki/软件安装/deepmd-kit_installation_191.md#安装tensorflow的c-接口

教程里提到新版本deepmd-kit依赖有问题，是什么问题，有解决嘛？
另外希望教程里有标注更新日期，因为我看到有好几个版本的安装教程，有点混乱。

**Comment by Cloudac7** [comment]
1. DeePMD-kit 2.1.0+版本目前确认按照这一步骤安装时会在Cmake步骤报错（报错信息如果我能找到也会贴在这里），且暂时没有解决。
2. 谢谢建议，我们加一下。目前没有关闭其他教程的原因是没有归档，且正在考虑迁移wiki到mkdocs原生实现。
