### ISSUE TITLE
About DPGen‘s workflow using GPU 

### ISSUE THREAD

**Issue by mast1986** [chenglabwiki/chenglabwiki.github.io#113]
嗨，我看到你们的wiki上有总结DPGen的workflow的使用经验，其中提到DFT单点能计算使用GPU，我想问一下，这部分使用GPU相比CPU有多少加速？另外，DPGen的training，model_devi，fp这三部分通常都在什么平台上运行的？
谢谢

**Comment by robinzyb** [comment]
请问是在哪看到的，贴一下链接。集群是大家都有贡献，我帮你问一下相应的同学

**Comment by mast1986** [comment]
> 请问是在哪看到的，贴一下链接。集群是大家都有贡献，我帮你问一下相应的同学

感谢回复，是这个链接：https://wiki.cheng-group.net/wiki/software_usage/experience_of_dpmd_and_dpgen/
![image](https://user-images.githubusercontent.com/51349378/194751546-7c83b8fc-51f4-4bc6-a979-8d40ff17eeeb.png)

感谢

**Comment by robinzyb** [comment]
fp是在cpu上运行的, training, model_devi在gpu。
另外GPU加速可参考:https://onlinelibrary.wiley.com/doi/10.1002/jcc.23096

**Comment by mast1986** [comment]
> fp是在cpu上运行的, training, model_devi在gpu。 另外GPU加速可参考:https://onlinelibrary.wiley.com/doi/10.1002/jcc.23096

谢谢，我想了解下，您看来，fp部分如果也在GPU上运行，使整个workflow都在gpu上，这会有什么帮助吗？我自己也尝试了一下。同时也想听听别人的想法。

**Comment by robinzyb** [comment]
除了加速，其他都是一样的。

**Comment by mast1986** [comment]
> 除了加速，其他都是一样的。

嗯，我看fp这个部分本身耗时是最长的，这部分加速对整个workflow的效率提升应该收益很大，只是我不是很清楚，现在dpgen在您所处的科研领域里，使用的频繁吗？是否是一个必备的工具？

**Comment by robinzyb** [comment]
看来原本的问题已经解决了。本issue主要对于wiki的内容提出问题，其他关于dpgen的应用及观点可以询问开发者。https://deepmodeling.com/detail/100
