### ISSUE TITLE
迁移到Mkdocs

### ISSUE THREAD

**Issue by Cloudac7** [chenglabwiki/chenglabwiki.github.io#114]
目前Wiki所使用的模板是基于Mkdocs移植的Jekyll实现，支持特性相对较少，且维护难度较大，产生链接文字过长。

考虑到Github Action可以提供基于Mkdocs的完整实现，迁移到原生项目实现，长远来看收益更大。

**Comment by robinzyb** [comment]
啥时候搞啊

**Comment by Cloudac7** [comment]
> 啥时候搞啊

目前先搞一个分支把现有的搬过去调试吧

**Comment by robinzyb** [comment]
支持！
