### ISSUE TITLE
Question: 类似unzip这种命令，断开ssh的话，解压会中断吗？

### ISSUE THREAD

**Issue by Xianyusyy** [chenglabwiki/chenglabwiki.github.io#117]
Question on: https://github.com/chenggroup/chenggroup.github.io/tree/master/_wiki/集群使用/ssh_note.md#使用ssh登录服务器
如题，数据集解压太慢了

**Comment by robinzyb** [comment]
会的。想要退出不中断命令参考: https://wiki.cheng-group.net/wiki/miscellaneous#run-process-when-you-logout-shell
