### ISSUE TITLE
对计算常见错误进行总结

### ISSUE THREAD

**Issue by Cloudac7** [chenglabwiki/chenglabwiki.github.io#123]
根据目前集群管理需要，推荐大家平时可以把自己遇到的常见报错信息和快速解决方法进行总结，从而最大程度方便大家自行修复或debug。

- [ ] CP2K
- [ ] DeePMD-kit
- [ ] DP-GEN
- [ ] VASP
- [ ] Lammps (Classical & DPMD)
- [ ] Plumed
- [ ] ASE
- [ ] MDAnalysis
- [ ] ...

**Comment by robinzyb** [comment]
"推荐大家平时可以把自己遇到的常见报错信息和快速解决方法进行总结"，具体的list.?

**Comment by robinzyb** [comment]
giscussion 自动开的讨论是不是就够了。
