### ISSUE TITLE
Expired figure in How To Do part.

### ISSUE THREAD

**Issue by Cloudac7** [chenglabwiki/chenglabwiki.github.io#158]
It seems that figure bed `tva1.sinaimg.cn` used in `howtodo.md` is now 403 forbidden, making it necessary to recover the expired figure. 
Just make it into an issue.

**Comment by robinzyb** [comment]
any alternative?

**Comment by Cloudac7** [comment]
> any alternative?

https://sm.ms/ might be OK.

**Comment by Cloudac7** [comment]
Solved in commit ce0290571937431c9a427d2d891ca6b806380966
