### ISSUE TITLE
something wrong about the use of dpgen

### ISSUE THREAD

**Issue by Normadp** [chenglabwiki/chenglabwiki.github.io#182]
The DPGEN Init Bulk process stopped after running Stage 3 without  error. Picture iis the information of dpgen.log and err
![fb86b19f8e7f54804626eefecac9140](https://github.com/user-attachments/assets/eb86cbba-4b33-48cb-a3ab-06ad81e2f293)
![66b3ef31b3f2420794f6d2c75ac057b](https://github.com/user-attachments/assets/60136095-9c04-4382-a46a-277908c7b617)

**Comment by robinzyb** [comment]
Please go to the dpgen repository.

**Comment by Normadp** [comment]
I'm sorry, I'm new here and I don't quite understand what you mean. Could you please explain it more clearly?



---- Replied Message ----
| From | Yong-Bin ***@***.***> |
| Date | 12/02/2024 16:45 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [chenggroup/chenggroup.github.io] something wrong about the use of dpgen (Issue #182) |

Please go to the dpgen repository.

**Comment by Normadp** [comment]
Sorry, I'm a newbie. I don't quite understand what you mean, I didn't find the dpgen repository, can you be more detailed?
![1733130964220](https://github.com/user-attachments/assets/7fbcb013-0783-4e3c-8ff3-7118afd3621d)

**Comment by robinzyb** [comment]
This is repository for wiki. Not for dpgen. please go to github dpgen  repository and rise the issue.
