### ISSUE TITLE
CP2K如何设置输出AIMD每一步每个原子位置、受力、能量到一个文件中？

### ISSUE THREAD

**Issue by ShangChien** [chenglabwiki/chenglabwiki.github.io#96]
Question on: https://github.com/chenggroup/chenggroup.github.io/tree/master/_wiki/Softwares Usage/cp2k-e-f.md#认识cp2k输入文件的主要部分
您好，我想要学习使用deepMD，选择cp2k作AIMD的calculator，如何设置输出AIMD每一步每个原子位置、受力、能量到一个文件中（类似vasprun.xml）？dpdata也正在学习中，不知道如何设置输出适合dpdata处理。希望前辈能给点建议，谢谢啦！

**Comment by robinzyb** [comment]
> Question on: https://github.com/chenggroup/chenggroup.github.io/tree/master/_wiki/Softwares Usage/cp2k-e-f.md#认识cp2k输入文件的主要部分
> 您好，我想要学习使用deepMD，选择cp2k作AIMD的calculator，如何设置输出AIMD每一步每个原子位置、受力、能量到一个文件中（类似vasprun.xml）？dpdata也正在学习中，不知道如何设置输出适合dpdata处理。希望前辈能给点建议，谢谢啦！

最近我将会对dpdata的cp2k部分进行一次重构，把cp2k input中FORCE_EVEL底下的PRINT FORCE打开就可以了，具体还是看一下cp2k手册
